import { GoogleGenAI, Modality } from "@google/genai";
// FIX: Removed the `declare global` block and `AIStudio` import. The global type for `window.aistudio` is now centralized in `types.ts` to resolve duplicate declaration errors.
import { ImageData, AspectRatio, GroundingChunk } from '../types';

const getAiClient = () => new GoogleGenAI({ apiKey: process.env.API_KEY as string });

export const generateInitialImage = async (prompt: string): Promise<ImageData> => {
  const ai = getAiClient();
  const response = await ai.models.generateImages({
    model: 'imagen-4.0-generate-001',
    prompt,
    config: {
      numberOfImages: 1,
      outputMimeType: 'image/png',
      aspectRatio: '1:1',
    },
  });

  const base64ImageBytes = response.generatedImages[0].image.imageBytes;
  return { base64: base64ImageBytes, mimeType: 'image/png' };
};

export const editImage = async (prompt: string, image: ImageData): Promise<ImageData> => {
  const ai = getAiClient();
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            data: image.base64,
            mimeType: image.mimeType,
          },
        },
        {
          text: prompt,
        },
      ],
    },
    config: {
      responseModalities: [Modality.IMAGE],
    },
  });

  for (const part of response.candidates[0].content.parts) {
    if (part.inlineData) {
      return { base64: part.inlineData.data, mimeType: part.inlineData.mimeType };
    }
  }

  throw new Error("No image was generated by the edit request.");
};


export const generateVideo = async (
    prompt: string, 
    image: ImageData, 
    aspectRatio: AspectRatio,
    setLoadingMessage: (message: string) => void
): Promise<string> => {
    const ai = getAiClient();
    setLoadingMessage("Initiating video generation...");
    let operation = await ai.models.generateVideos({
        model: 'veo-3.1-fast-generate-preview',
        prompt: prompt,
        image: {
            imageBytes: image.base64,
            mimeType: image.mimeType,
        },
        config: {
            numberOfVideos: 1,
            resolution: '720p',
            aspectRatio: aspectRatio,
        }
    });

    let pollCount = 0;
    while (!operation.done) {
        pollCount++;
        setLoadingMessage(`Synthesizing video... (Check ${pollCount}) This can take a few minutes.`);
        await new Promise(resolve => setTimeout(resolve, 10000));
        operation = await ai.operations.getVideosOperation({ operation: operation });
    }
    
    setLoadingMessage("Fetching generated video...");
    const downloadLink = operation.response?.generatedVideos?.[0]?.video?.uri;
    if (!downloadLink) {
        throw new Error("Video generation completed, but no download link was found.");
    }

    const response = await fetch(`${downloadLink}&key=${process.env.API_KEY}`);
    if (!response.ok) {
        throw new Error(`Failed to download video: ${response.statusText}`);
    }
    const videoBlob = await response.blob();
    return URL.createObjectURL(videoBlob);
};

export const getGroundedAnswer = async (prompt: string): Promise<{ text: string, sources: GroundingChunk[] }> => {
    const ai = getAiClient();
    const response = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents: prompt,
        config: {
            tools: [{ googleSearch: {} }],
        },
    });

    const text = response.text;
    const sources = response.candidates?.[0]?.groundingMetadata?.groundingChunks || [];
    return { text, sources };
};